{% set name = "fpdf2" %}
{% set version = "2.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/py-pdf/fpdf2/archive/refs/tags/{{ version }}.tar.gz
  sha256: b48a1d9826f8c307ddb5e0f5a0f838f3f4d18dbfcef14b98580ff3e7a870b801
  
build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - defusedxml
    - pillow >=8.0.0,!=9.2.*
    - fonttools >=4.34.0

{% set pytest_skip = [
  # Requires uharfbuzz
  "test_encryption_unicode",
  # Requires endesive
  "test_sign_pkcs12",
  "test_insert_jpg_jpxdecode",
  "test_insert_jpg_flatedecode",
  "test_insert_png_alpha_dctdecode",
  "test_page_background"
]%}
{% set pytest_ignore = [
  "--ignore=test/table/test_table_extraction.py",
  "--ignore=test/text_shaping",
  "--ignore=test/pdf-a/test_pdf_a.py",
  "--deselect=test/image/test_url_images.py::test_png_url",
  "--deselect=test/test_alias.py::test_alias_with_shaping",
  "--deselect=test/text_region/test_text_columns.py::test_text_columns_with_text_shaping",
  "--deselect=test/image/image_types/test_insert_images.py::test_insert_jpg_lzwdecode",
  "--deselect=test/text_region/test_text_columns.py::test_text_columns_with_shorter_2nd_column"
]%}
test:
  source_files:
    - test
    # Used in image tests
    - docs/fpdf2-logo.png
  imports:
    - fpdf
  commands:
    - pip check
    - pytest test {{pytest_ignore | join(" ")}} -k "not ({{ pytest_skip | join(" or ") }})"
  requires:
    - pip
    - pytest
    - pypdf
    - qrcode
    - cryptography
    - lxml

about:
  home: https://pyfpdf.github.io/fpdf2
  dev_url: https://github.com/PyFPDF/fpdf2
  doc_url: https://py-pdf.github.io/fpdf2
  summary: Simple PDF generation for Python
  description: |
    fpdf2 is a library for simple & fast PDF document generation 
    in Python. It is a fork and the successor of PyFPDF.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  license_family: LGPL

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
