{% set name = "fpdf2" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/py-pdf/fpdf2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 21e5671fe036b8be2a83519572bc5d3a43f418cb7923bfd64eaba080f8a7c6c6
  
build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - defusedxml
    - fonttools >=4.34.0
    - pillow >=6.2.2,!=9.2
    - python

test:
  source_files:
    - test
    # Used in image tests
    - docs/fpdf2-logo.png

  imports:
    - fpdf
  commands:
    - pip check
    {% set pytest_skip = "test_encryption_unicode" %} # Requires uharfbuzz
    {% set pytest_skip = pytest_skip + " or test_sign_pkcs12" %} # Requires endesive
    {% set pytest_skip = pytest_skip + " or test_insert_jpg_jpxdecode" %}
    {% set pytest_skip = pytest_skip + " or test_insert_jpg_flatedecode" %}
    {% set pytest_skip = pytest_skip + " or test_insert_png_alpha_dctdecode" %}
    {% set pytest_skip = pytest_skip + " or test_page_background" %}

    - pytest test --ignore=test/table/test_table_extraction.py --ignore=test/text_shaping -k "not ({{ pytest_skip }})"
  requires:
    - pip
    - pytest
    - qrcode
    - cryptography
    - lxml

about:
  home: https://pyfpdf.github.io/fpdf2/
  dev_url: https://github.com/PyFPDF/fpdf2
  doc_url: https://py-pdf.github.io/fpdf2/
  summary: Simple PDF generation for Python
  description: |
    fpdf2 is a library for simple & fast PDF document generation 
    in Python. It is a fork and the successor of PyFPDF.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
