{% set name = "fpdf2" %}
{% set version = "2.8.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/py-pdf/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: cabfa24a1daffc3ab6ed02ca2203b64cee33af573725bab46c133c79f42546c5
  
build:
  number: 1
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - fonttools ==4.63.0
  run:
    - python
    - defusedxml
    - pillow >=8.3.2,!=9.2.*
    - fonttools >=4.34.0

# Requires uharfbuzz
{% set pytest_skip = " test_encryption_unicode" %}
{% set pytest_skip = pytest_skip + " or test_noto_emoji_shaping" %}
{% set pytest_skip = pytest_skip + " or test_twemoji_shaping" %}
{% set pytest_skip = pytest_skip + " or test_noto_colrv1_shaping" %}
{% set pytest_skip = pytest_skip + " or test_twitter_emoji_shaping" %}
{% set pytest_skip = pytest_skip + " or test_add_font_woff_shaping" %}
{% set pytest_skip = pytest_skip + " or test_add_font_woff2" %}
{% set pytest_skip = pytest_skip + " or test_add_font_woff2_shaping" %}
{% set pytest_skip = pytest_skip + " or test_add_font_collection_shaping" %}

{% set pytest_skip = pytest_skip + " or test_add_font_symbol" %}  # [win]
{% set pytest_skip = pytest_skip + " or test_add_font_symbol_shaping" %}  # [win]

# Requires endesive
{% set pytest_skip = pytest_skip + " or test_encryption_unicode" %}
{% set pytest_skip = pytest_skip + " or test_sign_pkcs12" %}
{% set pytest_skip = pytest_skip + " or test_insert_jpg_jpxdecode" %}
{% set pytest_skip = pytest_skip + " or test_insert_jpg_flatedecode" %}
{% set pytest_skip = pytest_skip + " or test_insert_png_alpha_dctdecode" %}
{% set pytest_skip = pytest_skip + " or test_page_background" %}

{% set pytest_skip = pytest_skip + " or test_png_url" %}
{% set pytest_skip = pytest_skip + " or test_alias_with_shaping" %}
{% set pytest_skip = pytest_skip + " or test_text_columns_with_text_shaping" %}
{% set pytest_skip = pytest_skip + " or test_insert_jpg_lzwdecode" %}
{% set pytest_skip = pytest_skip + " or test_text_columns_with_shorter_2nd_column" %}

{% set pytest_ignore = " --ignore=test/table/test_table_extraction.py" %}
{% set pytest_ignore = pytest_ignore + " --ignore=test/text_shaping" %}
{% set pytest_ignore = pytest_ignore + " --ignore=test/pdf-a/test_pdf_a.py" %}

test:
  source_files:
    - test
    # Used in image tests
    - docs/fpdf2-logo.png
  imports:
    - fpdf
  commands:
    - pip check
    - pytest test -vv {{ pytest_ignore }} -k "not ({{ pytest_skip }})"
  requires:
    - pip
    - pytest
    - pypdf
    - brotli
    - qrcode
    - tabula-py
    - fonttools >=4.34.0
    - lxml
    - cryptography

about:
  home: https://pyfpdf.github.io/fpdf2
  dev_url: https://github.com/PyFPDF/fpdf2
  doc_url: https://py-pdf.github.io/fpdf2
  summary: Simple PDF generation for Python
  description: |
    fpdf2 is a library for simple & fast PDF document generation
    in Python. It is a fork and the successor of PyFPDF.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  license_family: LGPL

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
